### ISSUE TITLE
Question about KL divergence computation

### ISSUE THREAD

**Issue by Maxtoq** [vwxyzjn/lm-human-preference-details#25]
Hi there,

I have a question about the way you (and other implementations) compute the KL divergence penalty, by only taking the difference between log_probs and ref_log_probs:
https://github.com/vwxyzjn/lm-human-preference-details/blob/ba1a240567366ed58e182dde897dd1523a44ffd0/lm_human_preference_details/train_policy_accelerate.py#L628

From my understanding, the KL divergence is defined as the sum of probabilities times the difference between log_probs:
![image](https://github.com/vwxyzjn/lm-human-preference-details/assets/18440463/98865631-c96d-49b5-b2e7-cf9459e4e5cd)

Why is it that you don't compute it this way? 
I get the impression that this is linked to the fact that you compute the "per-token KL", but I don't really understand what this refers to.
Could you explain this a bit, please?

Thank you!

**Comment by vwxyzjn** [comment]
See http://joschu.net/blog/kl-approx.html

**Comment by liutianlin0121** [comment]
Thanks @Maxtoq for the interest! 

If we can enumerate all $x \in \mathcal{X}$, then we can indeed compute:

$$
D_{\text{KL}}(p\|q) = \sum_{x \in \mathcal{X}} p(x) \log[p(x)/q(x)]
$$

as you mentioned. Note that this is an equality. There is no approximation.


When $\mathcal{X}$ is very large, enumerating all $x$ can be expensive. Instead we can approximate the KL by rewriting it as an expectation

$$
D_{\text{KL}}(p\|q) = \mathbb{E}_{x \sim p(\cdot)} [\log p(x) - \log q(x)]
$$

By drawing a number of samples $x_i \sim  p(\cdot)$, we can approximate the expectation via an average of  $\log p(x_i) - \log q(x_i)$

**Comment by Maxtoq** [comment]
Okaaaay! Thank you I finally understand!
